# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import utils.models_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
            bases=(models.Model, utils.models_mixins.Signable, utils.models_mixins.Timestampable),
        ),
    ]
