# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.models_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
            },
            bases=(models.Model, utils.models_mixins.Signable, utils.models_mixins.Timestampable),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Lowest'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Highest')], default=1, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='task',
            name='todo_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.List', verbose_name='List'),
        ),
    ]
